repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.32.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.2"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell # See pyproject.toml for args
        additional_dependencies:
          - tomli

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: '0.26'
    hooks:
      - id: validate-pyproject
